name: fedoraland
description: Clean Hyprland.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
    install:
      packages:
        - sddm
        - network-manager-applet
        
        - nautilus
        - nautilus-python
        - glycin-thumbnailer
        - gvfs
        
        - google-chrome-stable
        - code
        
        - zsh
        - git
        - lsd
        - bat

        - adw-gtk3-theme 
        - qt6-qtwayland

  - type: script
    scripts:
      - setup-zsh.sh

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
    install:
      packages:
        - hyprland
        - hyprpaper
        - hyprlock
        - hypridle
        - xdg-desktop-portal-hyprland
        - hyprpolkitagent
        
        - grim
        - slurp
        - hyprshot
        - satty
        
        - wofi
        - kitty
        - hyprqt6engine

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - com.github.marhkb.Pods

          - org.gnome.Loupe
          - org.gnome.Showtime
          - org.gnome.Calculator
          - org.gnome.Papers
          - io.missioncenter.MissionCenter
          - io.github.getnf.embellish
          - ca.desrt.dconf-editor

          - com.discordapp.Discord
          - com.valvesoftware.Steam
      - scope: user

  - type: systemd
    system:
      enabled:
        - sddm
        - podman.socket

  - type: signing
