name: fedoraland
description: Clean Hyprland TTY.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: brew

  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
    install:
      packages:
        - zsh
        - git
        - nautilus
        - glycin-loaders
        - glycin-thumbnailer

        - gvfs
        - gvfs-smb

        - mesa-va-drivers

        - qt5-qtwayland
        - qt6-qtwayland

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
    install:
      packages:
        - hyprland
        - hyprland-qtutils

        - xdg-desktop-portal-hyprland
        - xdg-desktop-portal-gtk
        - hyprpolkitagent

        - hyprpaper
        - hyprlock
        - hypridle
        - hyprshot

        - kitty
        - wofi
        - waybar

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.github.fabrialberio.pinapp

      - scope: user

  - type: systemd
    system:
      enabled:
        - podman.socket

  - type: signing
