name: fedoraland
description: Clean Hyprland + GTK image (Dev Edition).

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - sddm
        - network-manager-applet
        
        - nautilus
        - nautilus-python
        - gvfs 
        
        - google-chrome-stable
        - code
        
        - zsh
        - util-linux-user
        - git
        - micro
        - ffmpeg-free

        - google-noto-sans-fonts
        - fira-code-fonts
        - adw-gtk3-theme 
        - qt6-qtwayland

  - type: script
    scripts:
      - setup-zsh.sh

  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
    install:
      packages:
        - hyprland
        - hyprpaper
        - hyprlock
        - hypridle
        - xdg-desktop-portal-hyprland
        - hyprpolkitagent
        - hyprpicker
        - hyprsunset
        - cliphist
        - pyprland
        - grim
        - slurp
        - hyprshot
        - satty
        - wofi
        - kitty
        - hyprqt6engine

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
      - scope: user

  - type: systemd
    system:
      enabled:
        - sddm
        - podman.socket

  - type: signing