name: fedoraland
description: Clean Hyprland.

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # System packages
  - type: dnf
    remove:
      packages:
        - firefox
        - firefox-langpacks
    install:
      packages:
        - sddm # Maybe change it

        - nautilus
        - nautilus-python
        - glycin-thumbnailer
        - gvfs

        - zsh
        - git
        - lsd # Hmmmm...
        - bat

        - qt6-qtwayland

  - type: dnf
    repos:
      copr:
        - errornointernet/quickshell
    install:
      packages:
        - quickshell

  # Hyprland packages
  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
    install:
      packages:
        - hyprland
        - hyprpaper
        - hyprlock
        - hypridle
        - xdg-desktop-portal-hyprland
        # - hyprpolkitagent # Search how custom
        - polkit-gnome
        - kitty

        # Screenshots packages
        # - grim
        # - slurp
        - hyprshot
        - satty

        - wofi

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # Flatpak tools
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.github.fabrialberio.pinapp

      - scope: user

  - type: systemd
    system:
      enabled:
        - sddm
        - podman.socket

  - type: signing
