name: FedoraLand
description: Clean Hyprland + GTK image (Fixed).

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # --- BLOCO 1: AJUSTES DO SISTEMA ---
  # Removemos tudo que já vem na base (podman, toolbox, pipewire, etc)
  # Mantemos apenas o que falta para transformar o servidor em desktop.
  - type: dnf
    install:
      packages:
        # --- Interface & Login ---
        - sddm
        - network-manager-applet
        
        # --- Suporte a Arquivos ---
        - gvfs 
        
        # --- Fontes & Temas ---
        - google-noto-sans-fonts
        - fira-code-fonts
        - adw-gtk3-theme 
        
        # --- Bibliotecas Gráficas ---
        # O Qt5 já veio instalado segundo o log, mantemos só o 6
        - qt6-qtwayland
        
        # --- Utilitários Extras ---
        # Git e Micro não deram erro de duplicidade, então mantemos
        - git
        - micro
        # ffmpeg-free não deu erro, mantemos para garantir codecs
        - ffmpeg-free

  # --- BLOCO 2: ECOSSISTEMA HYPRLAND ---
  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
    install:
      packages:
        # Core
        - hyprland
        - hyprpaper
        - hyprlock
        - hypridle
        - xdg-desktop-portal-hyprland
        - hyprpolkitagent
        
        # Produtividade
        - hyprpicker
        - hyprsunset
        - cliphist
        - pyprland
        
        # Screenshot (wl-clipboard, jq e libnotify já estão na base, removemos daqui)
        - grim
        - slurp
        - hyprshot
        - satty
        
        # Interface
        - wofi
        - kitty
        - hyprqt6engine

  # --- BLOCO 3: FLATPAKS ---
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Nautilus
      - scope: user

  # --- BLOCO 4: SERVIÇOS ---
  - type: systemd
    system:
      enabled:
        - sddm
        - podman.socket

  - type: signing